apiVersion: v1
kind: ConfigMap
metadata:
  name: private-creds-configmap
  labels:
    app.kubernetes.io/name: private-creds-configmap
    app.kubernetes.io/part-of: falco-event-generator
    falco.org/rule: Create.Modify-Configmap-With-Private-Credentials
data:
  ui.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
    password=some_secret_password
